### ISSUE TITLE
Wordpress - Gravity Form fields using conditional logic

### ISSUE THREAD

**Issue by J6a74** [mosparo/mosparo#295]
Gravity Form fields using conditional logic that end up staying hidden fail verification.

An example that I'm seeing this. 
A check box selection. 
Depending on what the check box/s is selected it will display different form fields.
The fields that remain hidden fail verification. 

I saw in the documentation you can add CSS "mosparo__ignored-field" to ignore (I don't need these fields verified). 
Gravity forms "custom CSS Class" looks to only add it to the container div however. Not the input its self so that doesn't work.

--
mosparo version 1.2.9

**Comment by zepich** [comment]
Hi @J6a74 

Thank you very much for your report.

If I understood you correctly, you have something like this:

![image](https://github.com/user-attachments/assets/335ebeb6-0cb7-40cf-ab62-0c1e2338f226)

Is that correct?

If I choose Option A, for example, fill out the field "Visible when Option A" and submit the form, everything works as expected. Do you see any error messages? If yes, where do you see the error? Do you have additional conditions or simply "Show field when Checkbox A is checked"?

The problem with the `mosparo__ignored-field` class is that Gravity Forms adds this class to the `<div>` container of the field and not to the field itself. I have to check how we can solve that with Gravity Forms - I didn't think about that when we developed the module.

I'm looking forward to your feedback.

Kind regards,

zepich

**Comment by J6a74** [comment]
The form for reference is https://cmicert.com.au/form-client-feed-back/ (mosparo is currently turned off)
This issue spot is the hidden select boxes that "Subject of the Feedback" check box's reveal.

![Image](https://github.com/user-attachments/assets/6c8aa0d4-11aa-4337-a9e5-041b6c7420ff)
![Image](https://github.com/user-attachments/assets/a543adb7-39a2-4554-88b5-ec836a56532a)
![Image](https://github.com/user-attachments/assets/90802873-2c53-423c-995a-f29cfd43ab1e)

Thought it might have been the default selected option - With the default  of 5
![Image](https://github.com/user-attachments/assets/5e92c482-da1d-4c62-9b85-fed969cbb7db)

With no default
![Image](https://github.com/user-attachments/assets/d2b47e4b-83a4-409a-b387-3c1ca4fbf0ab)

Probably another topic but I was also getting duplicated verification boxes on failure
![Image](https://github.com/user-attachments/assets/a1d35b4a-c3ab-46da-8f39-faaea6d5a046)

**Comment by zepich** [comment]
Hi @J6a74 

Thank you very much for your response and all the details.

I understand what the problem is and will investigate it. I will also have a look at the duplicated mosparo boxes.

I will inform you as soon as possible.

Kind regards,

zepich

**Comment by zepich** [comment]
Hi @J6a74 

Thank you very much for your report and the details you've provided.

I've found the issue and fixed it. We've just released v1.12.1, which handles conditionally hidden fields and fields with the CSS class `mosparo__ignored-field` correctly.

Please test it and tell me if that fixes your issues.

Kind regards,

zepich

**Comment by J6a74** [comment]
Hi @zepich 
Thanks for the quick patch. 
Still not quite working though. 
It now validates fine in the mosparo interface but the form still doesn't submit.

![Image](https://github.com/user-attachments/assets/efc5191c-511f-44a9-bc1a-fa8f02ce45be)

![Image](https://github.com/user-attachments/assets/172bd27e-ba06-45de-a658-51084c4932bc)

**Comment by zepich** [comment]
Hi @J6a74 

Thank you very much for your feedback.

Is this with the CSS class (`mosparo__ignored-field`) or just with the conditions? If it's just with the condition, can you try to use the class? And if it's with the class, can you try it without the class?

Thank you very much!

Kind regards,

zepich

**Comment by J6a74** [comment]
Same with or out without the mosparo__ignored-field 

I am seeing this in the console after clicking submit. 
![Image](https://github.com/user-attachments/assets/695e8812-4511-4a08-a2c5-8b75c9329b29)

**Comment by zepich** [comment]
Hi @J6a74 

Thank you very much for your response.

So, the JavaScript error is probably responsible for the two checkboxes after the verification. Let's tackle this issue after we've fixed the verification issue.

I've just tested the form on your site, and in the payload in the post request of Gravity Form, I see a field `gf_zero_spam_key`. Can you turn off that plugin to test it with mosparo?

![Image](https://github.com/user-attachments/assets/1571f61a-914b-41cb-abb2-71e3d71810dd)

Can you test it with a new, simple form with just two fields (with a checkbox and a conditional input field) to see if you have the same problem there?

Do you have custom field types in your form which are not standard Gravity Form field types?

Kind regards,

zepich

**Comment by J6a74** [comment]
Ok think I've narrowed it down.
I've created 3 test pages 

https://cmicert.com.au/mosparo-test-2/
Which has just a plain form which Works fine.

https://cmicert.com.au/mosparo-test/
Which has check boxes and hidden fields. 
1st check box unhides text 1 and drop down 1
2nd checkbox unhides text 2 and drop down 2

I've added the "mosparo__ignored-field" css to text 2 and drop down 2. 
This will then submit fine if only checkbox 1 is selected. 

However only selecting second checkbox which displays text2 and drop down 2
and leaving text 1 and dropdown 1 hidden which don't have "mosparo__ignored-field" css it will fail.

So looks like the hidden fields are what is catching it out. 
Earlier I only had "mosparo__ignored-field" css on the dropdowns as that was the field that the mosparo interface originally had issues with. 

I have now tried putting the ignore css on all the hidden fields but that didn't work either. 
So I recreated the feedback form and put it on a test page here https://cmicert.com.au/mosparo-test-feedback/
The original form was an old gravity form. With the new form I now get the same behavior as above.  

In short 
- Hidden forms without the "mosparo__ignored-field" css fail to submit the form but the mosparo interface will correctly ignore them regardless of ignore css.
- "mosparo__ignored-field" css doesn't appear to work correctly on forms created with an old gravity form.

**Comment by zepich** [comment]
Hi @J6a74 

Thank you very much for your very detailed feedback and testing.

With your description/explanation, I was able to reproduce the issue and add a fix for it.

We've just released v1.12.2 of the mosparo WordPress plugin, which fixes the issue with the conditional fields. Can you test this version?

In my previous attempt to fix the issue I've used a select field as conditionally hidden field, which does not have to be verified by mosparo. Because of this, I did not see that the issue was not fixed with v1.12.1.

Regarding the old Gravity Form form issue: I cannot reproduce it because my forms are all too new. Sorry for asking, but is it an option for you to export one of these older forms for me?

Thank you very much for your help, feedback, and hard work!

Kind regards,

zepich

**Comment by J6a74** [comment]
Thanks for the patch. 
Still not working on the old form but works on the new one. I'll switch over to the new form when I get the chance later in the week. 

This is an export of the old gravity form. Should be able to import per the documentation.
https://docs.gravityforms.com/importing-a-form-into-gravity-forms/
Not sure if this will give you exact copy or mutates into a new like form on import?

[gravityforms-export-2025-01-20.json](https://github.com/user-attachments/files/18483118/gravityforms-export-2025-01-20.json)

**Comment by zepich** [comment]
Hi @J6a74 

Thank you very much for your feedback. Great to hear!

Does the old form not work with conditional logic or the CSS class?

I will test your export, thank you very much!

Kind regards,

zepich
